# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    codeCoverageEnabled: false
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    publishRunAttachments: false

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Dynamic Code Coverage Tools"
      ls

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd "$(Agent.TempDirectory)\TestResults"
      ls

- task: CoverageConverter@0
  inputs:
    codeCoverageExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe'
    vsTestExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
    listTestFiles: '**\\bin\\**\\*.Tests*.dll'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd "$(Agent.TempDirectory)\TestResults"
      ls

- task: reportgenerator@4
  displayName: 'Generate Coverage Report'
  inputs:
    reports: '$(Agent.TempDirectory)\TestResults\DynamicCodeCoverage.coveragexml'
    targetdir: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'
    reporttypes: 'HtmlInline_AzurePipelines;Cobertura;Badges'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd "$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports"
      ls

- task: PublishCodeCoverageResults@1
  displayName: 'Publish Coverage Report'
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports\Cobertura.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports'


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd "$(System.DefaultWorkingDirectory)\TestResults\Coverage\Reports"
      ls